name: Copy File

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: diegoshalom/labosdf
          path: source-repo
          ref: master
      - name: Copy file to destination repository
        run: cp 'source-repo/software/python/intro comunicacion/instrumental.py' instrumental.py
      - name: Commit and push changes
        run: |
          git config --local user.email "javitau459@gmail.com"
          git config --local user.name "javidelrojoo"
          git add instrumental.py
          git commit -m "Copy instrumental.py from diegoshalom/labosdf repository"
          git push
